---
galaxy_info:
  role_name: test_role
  author: ghhalba
  description: A sample role to demonstrate Ansible Galaxy collection.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
